destination: ./_site
exclude: [.git, .gitignore]
auto:        true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
permalink: /blog/:year/:month/:day/:title	

title: "Ren Provey"